GET http://localhost:5245/games

###
GET http://localhost:5245/games/1

###
POST http://localhost:5245/games
Content-Type: application/json

{
    "name": "Final Fantasy XIV",
    "genreid": 3,
    "price": 49.99,
    "releaseDate": "2010-09-30"
}

###
PUT http://localhost:5245/games/1
Content-Type: application/json

{
    "name": "Minecraft II",
    "genreId": 2,
    "price": 9.99,
    "releaseDate": "2011-11-11"
}

###
DELETE http://localhost:5245/games/3 
